info:
  version: 0.0.1

spring:
  application:
    name: product

  main:
    banner-mode: off

  data:
    rest:
      detection-strategy: annotated

  session:
    store-type: jdbc

  liquibase:
    user: postgres
    password: password

  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

server:
  error.whitelabel.enabled: false
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
    context-path: /api

elastic:
  apm:
    service-name: product
    server-urls:
      - http://localhost:8200
    application-packages:
      - fr.bpifrance

application:
  services:
    api:
      basic-authentication:
        user: admin
        password: SOME_PASSWORD
