version: '3.1'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.221.0/24
